// List of all engine variables and their types.
// Used to generate VarPtr::var_name constants.

// TODO: assign appropriate types (arrays, structs, strings, etc.) for all variables

_VAR_(aiInfoList,                 DWORD)
_VAR_(ambient_light,              DWORD)
_VARA(art,                        sArt, 11)
_VAR_(art_name,                   DWORD)
_VAR_(art_vault_guy_num,          DWORD)
_VAR_(art_vault_person_nums,      DWORD)
_VAR_(bckgnd,                     BYTE*)
_VAR_(black_palette,              DWORD)
_VAR_(bottom_line,                DWORD)
_VAR_(btable,                     DWORD)
_VAR_(btncnt,                     DWORD)
_VAR_(CarCurrArea,                DWORD)
_VAR_(cmap,                       DWORD)
_VAR_(colorTable,                 DWORD)
_VAR_(combat_free_move,           DWORD)
_VAR_(combat_list,                DWORD)
_VAR_(combat_state,               DWORD)
_VAR_(combat_turn_running,        DWORD)
_VAR_(combatNumTurns,             DWORD)
_VAR3(crit_succ_eff,              CritStruct, 20, 9, 6)  // 20 critters with 9 body parts and 6 effects each
_VAR_(critter_db_handle,          DWORD)
_VAR_(critterClearObj,            DWORD)
_VAR_(crnt_func,                  DWORD)
_VAR_(curr_font_num,              DWORD)
_VARA(curr_pc_stat,               long, PCSTAT_max_pc_stat)
_VAR_(curr_stack,                 DWORD)
_VAR_(cursor_line,                DWORD)
_VAR_(dialog_target,              DWORD)
_VAR_(dialog_target_is_party,     DWORD)
_VAR_(drugInfoList,               DWORD)
_VAR_(edit_win,                   DWORD)
_VAR_(Educated,                   DWORD)
_VAR_(Experience_,                DWORD)
_VAR_(fallout_game_time,          DWORD)
_VAR_(flptr,                      DWORD)
_VAR_(folder_card_desc,           DWORD)
_VAR_(folder_card_fid,            DWORD)
_VAR_(folder_card_title,          DWORD)
_VAR_(folder_card_title2,         DWORD)
_VAR_(frame_time,                 DWORD)
_VAR_(free_perk,                  char)
_VAR_(game_global_vars,           long*)  // dynamic array of size == num_game_global_vars
_VAR_(game_user_wants_to_quit,    DWORD)
_VAR_(gcsd,                       DWORD)
_VAR_(gdBarterMod,                DWORD)
_VAR_(gdNumOptions,               DWORD)
_VAR_(gIsSteal,                   DWORD)
_VAR_(glblmode,                   DWORD)
_VAR_(gmouse_current_cursor,      DWORD)
_VAR_(gmovie_played_list,         DWORD)
_VAR_(GreenColor,                 BYTE)
_VAR_(gsound_initialized,         DWORD)
_VAR_(hit_location_penalty,       DWORD)
_VAR_(holo_flag,                  DWORD)
_VAR_(holopages,                  DWORD)
_VAR_(hot_line_count,             DWORD)
_VAR_(i_fid,                      DWORD)
_VAR_(i_lhand,                    DWORD)
_VAR_(i_rhand,                    DWORD)
_VAR_(i_wid,                      DWORD)
_VAR_(i_worn,                     DWORD)
_VAR_(idle_func,                  DWORD)
_VAR_(In_WorldMap,                DWORD)
_VAR_(info_line,                  DWORD)
_VAR_(interfaceWindow,            DWORD)
_VAR_(intfaceEnabled,             DWORD)
_VAR_(intotal,                    DWORD)
_VAR_(inven_dude,                 TGameObj*)
_VAR_(inven_pid,                  DWORD)
_VAR_(inven_scroll_dn_bid,        DWORD)
_VAR_(inven_scroll_up_bid,        DWORD)
_VAR_(inventry_message_file,      MessageList)
_VARA(itemButtonItems,            ItemButtonItem, 2) // 0 - left, 1 - right
_VAR_(itemCurrentItem,            long)  // 0 - left, 1 - right
_VAR_(kb_lock_flags,              DWORD)
_VAR_(last_buttons,               DWORD)
_VAR_(last_button_winID,          DWORD)
_VAR_(last_level,                 DWORD)
_VAR_(Level_,                     DWORD)
_VAR_(Lifegiver,                  DWORD)
_VAR_(list_com,                   DWORD)
_VAR_(list_total,                 DWORD)
_VAR_(loadingGame,                DWORD)
_VAR_(LSData,                     DWORD)
_VAR_(lsgwin,                     DWORD)
_VAR_(main_ctd,                   DWORD)
_VAR_(main_window,                DWORD)
_VAR_(map_elevation,              DWORD)
_VAR_(map_global_vars,            long*)  // array
_VAR_(master_db_handle,           DWORD)
_VAR_(max,                        DWORD)
_VAR_(maxScriptNum,               long)
_VAR_(Meet_Frank_Horrigan,        DWORD)
_VAR_(mouse_hotx,                 DWORD)
_VAR_(mouse_hoty,                 DWORD)
_VAR_(mouse_is_hidden,            DWORD)
_VAR_(mouse_x_,                   DWORD)
_VAR_(mouse_y,                    DWORD)
_VAR_(mouse_y_,                   DWORD)
_VAR_(Mutate_,                    DWORD)
_VAR_(name_color,                 DWORD)
_VAR_(name_font,                  DWORD)
_VAR_(name_sort_list,             DWORD)
_VAR_(num_game_global_vars,       DWORD)
_VAR_(num_map_global_vars,        DWORD)
_VAR_(obj_dude,                   TGameObj*)
_VAR_(objectTable,                DWORD)
_VAR_(objItemOutlineState,        DWORD)
_VAR_(optionRect,                 DWORD)
_VAR_(outlined_object,            DWORD)
_VAR_(partyMemberAIOptions,       DWORD)
_VAR_(partyMemberCount,           DWORD)
_VAR_(partyMemberLevelUpInfoList, DWORD)
_VAR_(partyMemberList,            DWORD*) // each struct - 4 integers, first integer - objPtr
_VAR_(partyMemberMaxCount,        DWORD)
_VAR_(partyMemberPidList,         DWORD)
_VAR_(patches,                    char*)
_VAR_(paths,                      sPath*)  // array
_VAR2(pc_crit_succ_eff,           CritStruct, 9, 6)  // 9 body parts, 6 effects
_VAR_(pc_kill_counts,             DWORD)
_VARA(pc_name,                    char, 32)
_VAR_(pc_proto,                   sProtoCritter)
_VARA(pc_trait,                   long, 2)  // 2 of them
_VARA(perk_data,                  PerkInfo, PERK_count)
_VAR_(perkLevelDataList,          long*) // dynamic array, limited to PERK_Count
_VAR_(pip_win,                    DWORD)
_VAR_(pipboy_message_file,        MessageList)
_VAR_(pipmesg,                    DWORD)
_VAR_(preload_list_index,         DWORD)
_VARA(procTableStrs,              const char*, ScriptProc::count)  // table of procId (from define.h) => procName map
_VARA(proto_msg_files,            MessageList, 6)  // array of 6 elements
_VAR_(proto_main_msg_file,        MessageList)  
_VAR_(ptable,                     DWORD)
_VAR_(pud,                        DWORD)
_VAR_(queue,                      DWORD)
_VAR_(quick_done,                 DWORD)
_VAR_(read_callback,              DWORD)
_VAR_(RedColor,                   BYTE)
_VARA(retvals,                    sElevator, 24)
_VAR_(scr_size,                   DWORD)
_VAR_(scriptListInfo,             ScriptListInfoItem*)  // dynamic array
_VARA(skill_data,                 SkillInfo, SKILL_count)
_VAR_(slot_cursor,                DWORD)
_VAR_(sneak_working,              DWORD) // DWORD var 
_VAR_(square,                     DWORD)
_VAR_(squares,                    DWORD*)
_VAR_(stack,                      DWORD)
_VAR_(stack_offset,               DWORD)
_VARA(stat_data,                  StatInfo, STAT_real_max_stat) // dynamic array
_VAR_(stat_flag,                  DWORD)
_VAR_(Tag_,                       DWORD)
_VAR_(tag_skill,                  DWORD)
_VAR_(target_curr_stack,          DWORD)
_VAR_(target_pud,                 DWORD)
_VAR_(target_stack,               DWORD)
_VAR_(target_stack_offset,        DWORD)
_VAR_(target_str,                 DWORD)
_VAR_(target_xpos,                DWORD)
_VAR_(target_ypos,                DWORD)
_VAR_(text_char_width,            DWORD)
_VAR_(text_height,                DWORD)
_VAR_(text_max,                   DWORD)
_VAR_(text_mono_width,            DWORD)
_VAR_(text_spacing,               DWORD)
_VAR_(text_to_buf,                DWORD)
_VAR_(text_width,                 DWORD)
_VAR_(title_color,                DWORD)
_VAR_(title_font,                 DWORD)
_VARA(trait_data,                 TraitInfo, TRAIT_count)
_VAR_(view_page,                  DWORD)
_VAR_(wd_obj,                     DWORD)
_VAR_(wmAreaInfoList,             DWORD)
_VAR_(wmLastRndTime,              DWORD)
_VAR_(wmWorldOffsetX,             DWORD)
_VAR_(wmWorldOffsetY,             DWORD)
_VAR_(world_xpos,                 DWORD)
_VAR_(world_ypos,                 DWORD)
_VAR_(WorldMapCurrArea,           DWORD)
_VAR_(YellowColor,                BYTE)

#undef _VAR_
#undef _VARP
#undef _VARA
#undef _VAR2
#undef _VAR3