// List of all engine variables and their types.
// Used to generate VarPtr::var_name constants.

// TODO: assign appropriate types (arrays, structs, strings, etc.) for all variables

_VAR(aiInfoList,                 DWORD)
_VAR(ambient_light,              DWORD)
_VAR(art,                        sArt)
_VAR(art_name,                   DWORD)
_VAR(art_vault_guy_num,          DWORD)
_VAR(art_vault_person_nums,      DWORD)
_VAR(bckgnd,                     DWORD)
_VAR(black_palette,              DWORD)
_VAR(bottom_line,                DWORD)
_VAR(btable,                     DWORD)
_VAR(btncnt,                     DWORD)
_VAR(CarCurrArea,                DWORD)
_VAR(cmap,                       DWORD)
_VAR(colorTable,                 DWORD)
_VAR(combat_free_move,           DWORD)
_VAR(combat_list,                DWORD)
_VAR(combat_state,               DWORD)
_VAR(combat_turn_running,        DWORD)
_VAR(combatNumTurns,             DWORD)
_VAR(crit_succ_eff,              CritStruct)  // static array
_VAR(critter_db_handle,          DWORD)
_VAR(critterClearObj,            DWORD)
_VAR(crnt_func,                  DWORD)
_VAR(curr_font_num,              DWORD)
_VAR(curr_pc_stat,               DWORD)
_VAR(curr_stack,                 DWORD)
_VAR(cursor_line,                DWORD)
_VAR(dialog_target,              DWORD)
_VAR(dialog_target_is_party,     DWORD)
_VAR(drugInfoList,               DWORD)
_VAR(edit_win,                   DWORD)
_VAR(Educated,                   DWORD)
_VAR(Experience_,                DWORD)
_VAR(fallout_game_time,          DWORD)
_VAR(flptr,                      DWORD)
_VAR(folder_card_desc,           DWORD)
_VAR(folder_card_fid,            DWORD)
_VAR(folder_card_title,          DWORD)
_VAR(folder_card_title2,         DWORD)
_VAR(frame_time,                 DWORD)
_VAR(free_perk,                  char)
_VAR(game_global_vars,           int*)  // array
_VAR(game_user_wants_to_quit,    DWORD)
_VAR(gcsd,                       DWORD)
_VAR(gdBarterMod,                DWORD)
_VAR(gdNumOptions,               DWORD)
_VAR(gIsSteal,                   DWORD)
_VAR(glblmode,                   DWORD)
_VAR(gmouse_current_cursor,      DWORD)
_VAR(gmovie_played_list,         DWORD)
_VAR(GreenColor,                 BYTE)
_VAR(gsound_initialized,         DWORD)
_VAR(hit_location_penalty,       DWORD)
_VAR(holo_flag,                  DWORD)
_VAR(holopages,                  DWORD)
_VAR(hot_line_count,             DWORD)
_VAR(i_fid,                      DWORD)
_VAR(i_lhand,                    DWORD)
_VAR(i_rhand,                    DWORD)
_VAR(i_wid,                      DWORD)
_VAR(i_worn,                     DWORD)
_VAR(In_WorldMap,                DWORD)
_VAR(info_line,                  DWORD)
_VAR(interfaceWindow,            DWORD)
_VAR(intfaceEnabled,             DWORD)
_VAR(intotal,                    DWORD)
_VAR(inven_dude,                 TGameObj*)
_VAR(inven_pid,                  DWORD)
_VAR(inven_scroll_dn_bid,        DWORD)
_VAR(inven_scroll_up_bid,        DWORD)
_VAR(inventry_message_file,      MessageList)
_VAR(itemButtonItems,            DWORD)
_VAR(itemCurrentItem,            DWORD)  // 0 - left, 1 - right
_VAR(kb_lock_flags,              DWORD)
_VAR(last_buttons,               DWORD)
_VAR(last_button_winID,          DWORD)
_VAR(last_level,                 DWORD)
_VAR(Level_,                     DWORD)
_VAR(Lifegiver,                  DWORD)
_VAR(list_com,                   DWORD)
_VAR(list_total,                 DWORD)
_VAR(loadingGame,                DWORD)
_VAR(LSData,                     DWORD)
_VAR(lsgwin,                     DWORD)
_VAR(main_ctd,                   DWORD)
_VAR(main_window,                DWORD)
_VAR(map_elevation,              DWORD)
_VAR(map_global_vars,            int*)  // array
_VAR(master_db_handle,           DWORD)
_VAR(max,                        DWORD)
_VAR(maxScriptNum,               DWORD)
_VAR(Meet_Frank_Horrigan,        DWORD)
_VAR(mouse_hotx,                 DWORD)
_VAR(mouse_hoty,                 DWORD)
_VAR(mouse_is_hidden,            DWORD)
_VAR(mouse_x_,                   DWORD)
_VAR(mouse_y,                    DWORD)
_VAR(mouse_y_,                   DWORD)
_VAR(Mutate_,                    DWORD)
_VAR(name_color,                 DWORD)
_VAR(name_font,                  DWORD)
_VAR(name_sort_list,             DWORD)
_VAR(num_game_global_vars,       DWORD)
_VAR(num_map_global_vars,        DWORD)
_VAR(obj_dude,                   TGameObj*)
_VAR(objectTable,                DWORD)
_VAR(objItemOutlineState,        DWORD)
_VAR(optionRect,                 DWORD)
_VAR(outlined_object,            DWORD)
_VAR(partyMemberAIOptions,       DWORD)
_VAR(partyMemberCount,           DWORD)
_VAR(partyMemberLevelUpInfoList, DWORD)
_VAR(partyMemberList,            DWORD*) // each struct - 4 integers, first integer - objPtr
_VAR(partyMemberMaxCount,        DWORD)
_VAR(partyMemberPidList,         DWORD)
_VAR(patches,                    char*)
_VAR(paths,                      sPath*)  // array
_VAR(pc_crit_succ_eff,           CritStruct)  // static array
_VAR(pc_kill_counts,             DWORD)
_VAR(pc_name,                    char)
_VAR(pc_proto,                   DWORD)
_VAR(pc_trait,                   DWORD)  // 2 of them
_VAR(pc_trait2,                  DWORD)
_VAR(perk_data,                  DWORD)
_VAR(perkLevelDataList,          int*) // limited to PERK_Count
_VAR(pip_win,                    DWORD)
_VAR(pipboy_message_file,        MessageList)
_VAR(pipmesg,                    DWORD)
_VAR(preload_list_index,         DWORD)
_VAR(procTableStrs,              const char*)  // table of procId (from define.h) => procName map
_VAR(proto_msg_files,            MessageList)  // array of 6 elements
_VAR(proto_main_msg_file,        MessageList)  
_VAR(ptable,                     DWORD)
_VAR(pud,                        DWORD)
_VAR(queue,                      DWORD)
_VAR(quick_done,                 DWORD)
_VAR(read_callback,              DWORD)
_VAR(RedColor,                   BYTE)
_VAR(retvals,                    DWORD)
_VAR(scr_size,                   DWORD)
_VAR(scriptListInfo,             DWORD)
_VAR(skill_data,                 SkillInfo)
_VAR(slot_cursor,                DWORD)
_VAR(sneak_working,              DWORD) // DWORD var 
_VAR(square,                     DWORD)
_VAR(squares,                    DWORD*)
_VAR(stack,                      DWORD)
_VAR(stack_offset,               DWORD)
_VAR(stat_data,                  DWORD)
_VAR(stat_flag,                  DWORD)
_VAR(Tag_,                       DWORD)
_VAR(tag_skill,                  DWORD)
_VAR(target_curr_stack,          DWORD)
_VAR(target_pud,                 DWORD)
_VAR(target_stack,               DWORD)
_VAR(target_stack_offset,        DWORD)
_VAR(target_str,                 DWORD)
_VAR(target_xpos,                DWORD)
_VAR(target_ypos,                DWORD)
_VAR(text_char_width,            DWORD)
_VAR(text_height,                DWORD)
_VAR(text_max,                   DWORD)
_VAR(text_mono_width,            DWORD)
_VAR(text_spacing,               DWORD)
_VAR(text_to_buf,                DWORD)
_VAR(text_width,                 DWORD)
_VAR(title_color,                DWORD)
_VAR(title_font,                 DWORD)
_VAR(trait_data,                 DWORD)
_VAR(view_page,                  DWORD)
_VAR(wd_obj,                     DWORD)
_VAR(wmAreaInfoList,             DWORD)
_VAR(wmLastRndTime,              DWORD)
_VAR(wmWorldOffsetX,             DWORD)
_VAR(wmWorldOffsetY,             DWORD)
_VAR(world_xpos,                 DWORD)
_VAR(world_ypos,                 DWORD)
_VAR(WorldMapCurrArea,           DWORD)
_VAR(YellowColor,                BYTE)

#undef _VAR