procedure start; 
// adjust include paths if needed
#include "..\..\scripting_docs\headers\sfall.h" 

#define RESULT_SUCCESS  (1)
#define RESULT_FAIL     (0)
 
procedure start begin 
   if not init_hook then begin
      variable
         thief := get_sfall_arg,
         target := get_sfall_arg,
         item := get_sfall_arg,
         action := get_sfall_arg,
         result := RESULT_SUCCESS;
      
      if (thief == dude_obj) then begin 
         display_msg(sprintf(mstr_skill(570 + result + action*2), obj_name(item))); 
         set_sfall_return(result); 
      end 
   end 
end
